version: "3.9-slim"
services:
  db:
    container_name: db
    image: postgres:16.6
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: milf55
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: user-service-app
    image: service/user-service-app
    restart: always
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
